// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250710205338_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ChickenBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CollectionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FarmStockId")
                        .HasColumnType("int");

                    b.Property<int>("FarmerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfChickens")
                        .HasColumnType("int");

                    b.Property<double>("QuantityInKg")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FarmerId");

                    b.ToTable("ChickenBatches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollectionDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            FarmStockId = 1,
                            FarmerId = 1,
                            Notes = "",
                            NumberOfChickens = 50,
                            QuantityInKg = 300.0,
                            Status = "InStock",
                            Type = "Broiler"
                        },
                        new
                        {
                            Id = 2,
                            CollectionDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            FarmStockId = 1,
                            FarmerId = 2,
                            Notes = "",
                            NumberOfChickens = 40,
                            QuantityInKg = 200.0,
                            Status = "Dispatched",
                            Type = "Layer"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("FarmStockId")
                        .HasColumnType("int");

                    b.Property<double>("RemainingWeight")
                        .HasColumnType("float");

                    b.Property<double>("TotalWeightLoaded")
                        .HasColumnType("float");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("FarmStockId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Deliveries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = "Market Area",
                            DeliveryDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            DriverId = 1,
                            FarmStockId = 1,
                            RemainingWeight = 0.0,
                            TotalWeightLoaded = 250.0,
                            VehicleId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ravi",
                            PhoneNumber = "999-888-7777"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Farmers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactPerson = "Ramu",
                            Location = "Brampton",
                            Name = "Ramu",
                            PhoneNumber = "111-222-3333"
                        },
                        new
                        {
                            Id = 2,
                            ContactPerson = "Kumar",
                            Location = "Brampton",
                            Name = "Kumar",
                            PhoneNumber = "222-333-4444"
                        });
                });

            modelBuilder.Entity("Domain.Entities.FarmStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FarmId")
                        .HasColumnType("int");

                    b.Property<int>("NoOfChickens")
                        .HasColumnType("int");

                    b.Property<double>("QuantityAvailableInKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("FarmStocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            NoOfChickens = 250,
                            QuantityAvailableInKg = 500.0
                        });
                });

            modelBuilder.Entity("Domain.Entities.MiscExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MiscExpenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 300m,
                            Date = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Ice Packing"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BalanceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("QuantityInKg")
                        .HasColumnType("float");

                    b.Property<decimal>("RatePerKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("ShopId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BalanceAmount = 0m,
                            DeliveryId = 1,
                            OrderDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            PaidAmount = 20000m,
                            QuantityInKg = 150.0,
                            RatePerKg = 150m,
                            ShopId = 1,
                            TotalAmount = 0m
                        },
                        new
                        {
                            Id = 2,
                            BalanceAmount = 0m,
                            DeliveryId = 1,
                            OrderDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            PaidAmount = 12000m,
                            QuantityInKg = 100.0,
                            RatePerKg = 160m,
                            ShopId = 2,
                            TotalAmount = 0m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModeOfPayment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ShopId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountPaid = 20000m,
                            ModeOfPayment = "Cash",
                            OrderId = 1,
                            PaymentDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            ShopId = 1
                        },
                        new
                        {
                            Id = 2,
                            AmountPaid = 12000m,
                            ModeOfPayment = "UPI",
                            OrderId = 2,
                            PaymentDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            ShopId = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Street 1",
                            ContactNumber = "444-555-6666",
                            ShopName = "Fresh Chicken"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Street 2",
                            ContactNumber = "555-666-7777",
                            ShopName = "Meat Mart"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TransportCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<int>("ExpenseType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("VehicleId");

                    b.ToTable("TransportCosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 150.00m,
                            Date = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            DeliveryId = 1,
                            ExpenseType = 0,
                            Notes = "Filled 30L diesel",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 500.00m,
                            Date = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            DeliveryId = 1,
                            ExpenseType = 1,
                            Notes = "Driver daily wage",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 70.00m,
                            Date = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            DeliveryId = 1,
                            ExpenseType = 3,
                            Notes = "Highway toll",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 200.00m,
                            Date = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            ExpenseType = 2,
                            Notes = "Oil change and check-up",
                            VehicleId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNo = "+917200806208",
                            FirstName = "Visu",
                            LastName = "",
                            Location = "Marandahalli",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            ContactNo = "+917200806208",
                            FirstName = "Visu1",
                            LastName = "",
                            Location = "Marandahalli",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            Role = "Driver",
                            Username = "driver1"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CapacityInKg")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacityInKg = 400.0,
                            Type = "Small Van",
                            VehicleNumber = "TN01AA1234"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ChickenBatch", b =>
                {
                    b.HasOne("Domain.Entities.Farm", "Farmer")
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("Domain.Entities.Delivery", b =>
                {
                    b.HasOne("Domain.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FarmStock", "FarmStock")
                        .WithMany()
                        .HasForeignKey("FarmStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("FarmStock");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Domain.Entities.FarmStock", b =>
                {
                    b.HasOne("Domain.Entities.Farm", null)
                        .WithMany("FarmStocks")
                        .HasForeignKey("FarmId");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.HasOne("Domain.Entities.Delivery", "Delivery")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Shop", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("Domain.Entities.TransportCost", b =>
                {
                    b.HasOne("Domain.Entities.Delivery", "Delivery")
                        .WithMany("TransportCosts")
                        .HasForeignKey("DeliveryId");

                    b.HasOne("Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Domain.Entities.Delivery", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("TransportCosts");
                });

            modelBuilder.Entity("Domain.Entities.Farm", b =>
                {
                    b.Navigation("FarmStocks");
                });
#pragma warning restore 612, 618
        }
    }
}
